# Generated by Django 3.2.3 on 2024-01-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ('name',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='measure',
            new_name='measurement_unit',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='title',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='name',
            field=models.CharField(default=1, max_length=150, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='ingredients',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='ingredient_name_unit_unique'),
        ),
    ]
