# Generated by Django 3.2.3 on 2024-02-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0003_favourite_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
